import Head from "next/head";
import Image from "next/image";
import { RouterOutputs, api } from "~/utils/api";
import { SignIn, useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import { Header } from "~/components/Header";
import dayjs from "dayjs"
import relativeTime from "dayjs/plugin/relativeTime"

dayjs.extend(relativeTime)

const CreatePostForm = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <form className="flex">
      <input
        placeholder="type some emojis!"
        className="grow bg-transparent outline-none"
      />
    </form>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div
      key={post.id}
      className="flex items-center gap-2 rounded border border-gray-500/50 p-2"
    >
      <Image
        className="h-10 w-10 rounded-full"
        src={author.profileImageUrl}
        alt={`${author.username} profile picture`}
        height={56}
        width={56}
        placeholder="blur"
      />
      <div className="flex flex-col">
        <div className="text-gray-400">
          <span className="">{`@${author.username}`}</span>
          <span className="font-thin">{` • ${dayjs(post.createdAt).fromNow()}`}</span>
          </div>
        <div>{post.content}</div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { data, isLoading, error } = api.posts.getAll.useQuery();

  const user = useUser();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>{error.message}</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <div className="container flex w-full flex-col">
          <Header />
          <CreatePostForm />
          <div className="flex flex-col gap-2">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
